<?php

return [
    'role_priority' => [
        'super_admin',
        'admin',
        'content_editor',
        'listing_editor',
        'listing_owner',
        'support_agent',
        'customer',
        'viewer',
    ],
    'roles' => [
        'super_admin' => ['*'],
        'admin' => [
            'admin.access',
            'pages.manage',
            'categories.manage',
            'listings.manage',
            'city_pages.manage',
            'admin.feedback.view',
            'admin.feedback.manage',
            'owner.access',
            'customer.access',
            'support.access',
            'owner.leads.manage',
            'support.requests.manage',
            'owner.feedback.view',
            'owner.feedback.manage',
            'customer.feedback.view',
            'customer.feedback.create',
            'customer.message.view',
        ],
        'content_editor' => [
            'admin.access',
            'pages.manage',
            'categories.manage',
            'listings.manage',
        ],
        'listing_editor' => [
            'admin.access',
            'listings.manage',
        ],
        'listing_owner' => [
            'owner.access',
            'owner.listings.manage',
            'owner.leads.view',
            'owner.leads.manage',
            'owner.feedback.view',
            'owner.feedback.manage',
            'customer.access',
            'customer.requests.create',
            'customer.requests.view',
            'customer.feedback.create',
            'customer.feedback.view',
            'customer.message.view',
        ],
        'customer' => [
            'customer.access',
            'customer.requests.create',
            'customer.requests.view',
            'customer.feedback.create',
            'customer.feedback.view',
            'customer.message.view',
        ],
        'support_agent' => [
            'support.access',
            'support.requests.view',
            'support.requests.manage',
        ],
        'viewer' => [
            'admin.access',
        ],
    ],
];
